### PR TITLE
Extract git history from go-kit/kit/log

### PR DESCRIPTION
**Pull request by peterbourgon**
I followed [this guide](https://banzaicloud.com/blog/decomposing-a-central-helm-chart-repository/) (thanks @sagikazarmark!) and I think got everything working...

### CODE REVIEW

**Comment by ChrisHines** [comment]
The commit history for this branch is unusual because it has multiple root commits. Of course git can handle it fine, but it makes for a strange PR due to the lack of a common merge base with the main branch.

How much do we care about that? If we want a more typical looking commit history I'm sure we could make that happen with a little history surgery and a force push to the main branch. That is usually an unsavory step, but it seems OK to me given the warning label @peterbourgon put in the initial README and the intentions of extracting the module here.

My vote would be for cleaning up the history, and I'm willing to do the work. I would stage it in a repo under my account for review before force pushing it here, but I'll wait to see what others think before proceeding.

**Comment by ChrisHines** [comment]
I have created a private repo to stage my work and sent invites to @peterbourgon and @sagikazarmark so you can each review the commit history there.

The procedure I applied was to start with 5e1beb4185ab4a037fc1e30819d8d791835702e4 and rebase the extract branch onto it to get a linear history of the work @peterbourgon has already done here. Then I interactively rebased the last few commits to squash some redundant history and update the commit messages to reflect the changes actually made in the updated commits.

The updated commit history eliminates the annoying `rm -rf` step and merge commit of two unrelated branches. The result is all of the old kit/log history followed by two commits:

1. The import path updates, GH actions, gofmt and staticcheck cleanup.
2. The deletion of the packages we're dropping.

If I get sign off on that history I can bring it over to this repo with a force push to the main branch and we can proceed from there.

**Comment by sagikazarmark** [comment]
Since this is a new repository and not an existing one, I think you can skip merging unrelated branches. In my case I had to merge the tree into an existing repo, so it made sense there, probably doesn't in this case.

The history looks good to me.

Can I ask what's the reason behind dropping those packages? I have a few guesses of course (eg. don't want to maintain them/add them as a dependency), but I think I would move the last commit to a separate PR to better document it. If someone looks at the repo, they won't find any reasoning why those packages were dropped.

**Comment by ChrisHines** [comment]
> I think I would move the last commit to a separate PR to better document it.

That is a good suggestion. I can push that commit as a separate branch and we can make it into a PR.

**Comment by peterbourgon** [comment]
Fine by me.

**Comment by ChrisHines** [comment]
OK. I will push the updated history here soon. I will create a new branch to preserve the existing commits until we confirm everything is good.

**Comment by ChrisHines** [comment]
Check that, the existing `extract` branch will already do the job of keeping the existing history around until we're happy with everything.

**Comment by peterbourgon** [comment]
I can't easily predict — will the force push blow away [the v0.0.1-alpha tag](https://github.com/go-kit/log/releases/tag/v0.0.1-alpha)?

**Comment by ChrisHines** [comment]
No, the tag is a separate thing and will also preserve the commit it tags. It would have to be deleted separately.

Also, it looks like I don't have permissions to push to the main branch on this repo or access to change that. So I'll need some help.

**Comment by peterbourgon** [comment]
@ChrisHines You should have them now, or perhaps an invite pending to gain them.

**Comment by ChrisHines** [comment]
OK. New main branch pushed and PR #3 created to trim out packages we are dropping.

**Comment by ChrisHines** [comment]
Closing now that #3 is merged.

**Comment by peterbourgon** [comment]
To be clear — we are deliberately not deleting the `extract` branch until we're satisfied with the state of the repo.

**Pull request closed without merging**
